# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companies',
            name='enlisted_papers',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
