# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfi', '0002_auto_20180223_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calc_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('issued_number', models.IntegerField(default=0)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enlistment_date', models.DateTimeField(auto_now_add=True)),
                ('zse_mark', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='enlisted_papers',
            new_name='securities_list',
        ),
        migrations.AddField(
            model_name='companies',
            name='zse_mark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='securities',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.Companies'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.Companies'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.IndicatorTypes'),
        ),
    ]
