# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfi', '0003_auto_20180226_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='currency',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
