# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfi', '0004_securities_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='security_type',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
