# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfi', '0005_securities_security_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('volume', models.IntegerField(blank=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPricesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('volume', models.IntegerField(blank=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockIndexMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(blank=True, max_length=1)),
                ('free_float_factor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_facor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockIndexTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='gfiheaders',
            name='is_consolidated',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gfiheaders',
            name='is_revised',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gfiheaders',
            name='period',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='abbreviation',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='indicatortypes',
            name='mark',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='aop_mark',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='mark',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='indicators',
            index=models.Index(fields=['company', 'calc_date'], name='indicators__company__calc_date'),
        ),
        migrations.AddIndex(
            model_name='indicators',
            index=models.Index(fields=['calc_date', 'company'], name='indicators__calc_date__company'),
        ),
        migrations.AddIndex(
            model_name='gfiheaders',
            index=models.Index(fields=['company', 'year'], name='gfi_headers__company__year'),
        ),
        migrations.AddIndex(
            model_name='gfiheaders',
            index=models.Index(fields=['year', 'company'], name='gfi_headers__year__company'),
        ),
        migrations.AddField(
            model_name='stockindexmembers',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.Securities'),
        ),
        migrations.AddField(
            model_name='stockindexmembers',
            name='stock_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.StockIndexTypes'),
        ),
        migrations.AddField(
            model_name='securitypriceshistory',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.Securities'),
        ),
        migrations.AddField(
            model_name='securityprices',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfi.Securities'),
        ),
        migrations.AddIndex(
            model_name='securitypriceshistory',
            index=models.Index(fields=['date', 'security'], name='sec_pric_hist__date__security'),
        ),
        migrations.AddIndex(
            model_name='securitypriceshistory',
            index=models.Index(fields=['security', 'date'], name='sec_pric_hist__security__date'),
        ),
    ]
